Traceback (most recent call last):
  File "main.py", line 79, in <module>
    main()
  File "main.py", line 61, in main
    plt.set_yscale("log")
AttributeError: module 'matplotlib.pyplot' has no attribute 'set_yscale'
